# Port
quarkus.http.port=8081

# Microservice url
izdelek.url=http://localhost:8080/graphql
skladisce.url=http://localhost:8082/v1/skladisce

# PostgreSQL Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.health.enabled=true

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.packages=si.nakupify.entity

# gRPC
quarkus.grpc.server.port=9001
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.codegen.input-dir="src/main/proto"
quarkus.grpc.codegen.output-dir="target/generated-sources/grpc"

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=*
quarkus.http.cors.access-control-allow-credentials=true

# OpenAPI Info
quarkus.smallrye-openapi.info-title=Kosarica
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Mikrostoritev za upravljanje kosaric uporabnikov.
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

# Swagger UI
quarkus.swagger-ui.always-include=true

# Keycloak OIDC
#quarkus.oidc.auth-server-url=http://localhost:8080/auth/realms/myrealm
#quarkus.oidc.client-id=my-client
#quarkus.oidc.credentials.secret=my-secret
#quarkus.oidc.tls.verification=none
#quarkus.oidc.application-type=service